{% set name = "pyaxiom" %}
{% set version = "1.3.1" %}
{% set build = 0 %}
{% set sha256 = "6ff60ce29e6792a015b904627f7a576b5fb3728ef6e4598c629ed83007974539" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/axiom-data-science/pyaxiom/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - binner=pyaxiom.netcdf.grids.binner:run

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pytz
        - python-dateutil
        - netcdf4
        - pandas
        - pyncml
        - pynco  # [not win]
        - simplejson

test:
    imports:
        - pyaxiom
        - pyaxiom.netcdf
        - pyaxiom.netcdf.grids
        - pyaxiom.netcdf.sensors
        - pyaxiom.tests
    commands:
        - binner --help

about:
    home: https://github.com/axiom-data-science/pyaxiom
    license: MIT
    summary: 'An ocean data toolkit developed and used by Axiom Data Science.'

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
