travis:
  secure:
    BINSTAR_TOKEN: Wlv2z61hTdxmn1adTZoJp0y84egmZtPk0WGqqTxe0kcGO2jj3/Lu7vcuimnk9S5Vihr0wNvEYwocbimArvVCPcfJj6FgvkHUhIvcWLtKBcMuoP8/i+lFV1edVkuDZmisM20x3oFWOQjsc2C4dtxSlCZBYxdvFjpgBWmbFQ0sysWbz3mwnVx/LR7zAM/jGcUxybE2emVthWBDqqvzGwa/q6DvZsHvcvwtwf9kueqSNVsBLB4UeyQ8Rkkr6PUjIB/v0hAX4OZsAyEKUC3JJlHYnjjkXstIzWSI6KBguJS1jR0oGUtY4QiKtD1autB9g2pH7Ber2+Jd6YfRdoPBV36z3eG2pZs9CkC1POkTaRIZJciL2vlwco/OISKdxeyuxlrGMKXM9MKX8daf5K1hXnnSnq8xdmWMuz4Fvovp/k1sulyLmA+mzPuXHA69j5SUYIAkLOtOVz6AWk+b0TYfRBI2phu0XRuhcmi/L63dlJ+rO1S9ke9L9cm33C2pAQRqRuZwiXZNi4WxqxKoNhaqEWSoWCKlmWr/jSZWQ2sRzz5qDCT0xDBajPvS+10P1fZDVVmrk8YepK1TjNGqOQw5qtHc6+eH14MhWiXs9fLGnDyfRag0CGbPVZxwIAcNuzLcjoBedt8K8dieTMjrqbVVwY03KRJgPXQaZ3ayfk2z9cWDfDU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
